import {
  ConflictsArray,
} from "../utils";

export const divConfig = [{
    name: "1st XI Premier",
    teams: [
      "BRE1",
      "BUC1",
      "CHE1",
      "CHI1",
      "COL1",
      "HAD1",
      "HOR1",
      "HUT1",
      "LOU1",
      "WAN1",
    ],
  }, {
    name: "1st XI Div 1",
    teams: [
      "BEL1",
      "BIL1",
      "EPP1",
      "FIV1",
      "GPR1",
      "HAW1",
      "ILF1",
      "ORS1",
      "SPR1",
      "UPM1",      
    ],
  }, {
    name: "1st XI Div 2",
    teams: [
      "AZT1",
      "GOR1",
      "HOH1",
      "OPA1",
      "OBR1",
      "OSS1",
      "SHE1",  
      "WOS1",
      "WGR1",
      "WWE1"
    ],
  }, {
    name: "1st XI Div 3",
    teams: [      
      "BAR1",
      "BEN1",
      "BNT1",
      "HAR1",
      "HAT1",
      "LOS1",
      "NEW1",
      "SLH1",
      "WFG1",
      "WES1",
    ],
  }, {
    name: "2nd XI Premier",
    teams: [
      "BIL2",
      "CHE2",
      "CHI2",
      "EPP2",
      "HAW2",
      "HOR2",
      "ILF2",
      "SHE2",
      "UPM2",
      "WAN2",
    ],
  }, {
    name: "2nd XI Div 1",
    teams: [
      "BRE2",
      "BUC2",
      "GPR2",
      "HAR2",
      "HUT2",
      "LOU2",
      "OPA2",
      "ORS2",
      "SWD2",
      "WWE2",
    ],
  }, {
    name: "2nd XI Div 2",
    teams: [
      "BEN2",
      "COL2",
      "FIV2",
      "HAD2",
      "OBR2",
      "OSS2",
      "SLH2",
      "WES2",
      "WOS2",
      "WIC2",
    ],
  }, {
    name: "2nd XI Div 3",
    teams: [
      "BEL2",
      "FRE2",
      "GOR2",
      "HAT2",
      "HOH2",
      "LOS2",
      "NEW2",
      "SOS2",
      "WAL2",
      "WGR2",
    ],
  }, {



  name: "3rd XI Premier",
  teams: [
    "BRE3",
    "CHE3",
    "HAR3",
    "HAW3",
    "ILF3",
    "SHE3",
    "UPM3",
    "WAN3",
    "WES3",
    "WWE3",
  ],
}, {
    name: "3rd XI Div 1",
    teams: [
      "CHI3",
      "FRE3",
      "GPR3",
      "HAT3",
      "HOR3",
      "HUT4",
      "OPA3",
      "ORS3",
      "SWF3",
      "UPM3",
    ],
  }, {
  name: "3rd XI Div 2",
  teams: [
    "BEN3",
    "BIL3",
    "BRE4",
    "BUC3",
    "CHE4",
    "FIV3",
    "HAR4",
    "HAW4",
    "LOU3",
    "WIC3",
  ],
}, {
  name: "3rd XI Div 3",
  teams: [
    "BEL3",
    "BUC4",
    "EPP3",
    "HOH3",
    "OBR3",
    "OSS3",
    "SLH3",
    "WAL3",
    "WAN4",
    "WES3",
  ],
}, {
  name: "4th XI Prem East",
  teams: [
    "BEN4",
    "BIL4",
    "HOH4",
    "HUT4",
    "LOS3",
    "LOS4",
    "ORS4",
    "SHE4",
    "SOS3",
    "WOS4",
  ],
}, {
  name: "4th XI Prem West",
  teams: [
    "CHI4",
    "FIV4",
    "FRE4",
    "ILF4",
    "LOU4",
    "OPA4",
    "UPM5",
    "WAL4",
    "WES4",
    "WGR4",
  ],
}, {
  name: "4th XI Div 1 East",
  teams: [
    "BIL5",
    "CHE5",
    "HAD4",
    "HAW5",
    "HOR4",
    "ORS5",
    "ORS6",
    "SLH4",
    "WOS5",
    "WIC4",
  ],
}, {
  name: "4th XI Div 1 West",
  teams: [
    "BEL4",
    "FRE5",
    "GPR4",
    "GOR3",
    "NEW3",
    "OPA5",
    "SWF4",
    "WAL5",
    "WAN5",
    "WAN6",
  ],
}, {
  name: "4th XI Div 2 East",
  teams: [
    "BEN5",
    "BRE6",
    "HOR5",
    "HOH5",
    "HUT5",
    "OSS4",
    "OSS5",
    "SHE5",
    "SOS4",
    "WIC5",
  ],
}, {
  name: "4th XI Div 2 West",
  teams: [
    "BAR3",
    "BEL5",
    "BRE5",
    "HAW6",
    "ILF5",
    "NEW4",
    "ORS7",
    "RED3",
    "RED4",
    "UPM6",
  ],
}];

export const venConflicts: ConflictsArray = [
  ["ARD1", "ARD2"],
  ["ARD3", "ARD4"],
  ["BEL1", "BEL2"],
  ["BEL3", "BEL4"],
  ["BEN1", "BEN2"],
  ["BEN3", "BEN4"],
  ["BIL1", "BIL2"],
  ["BIL3", "BIL4"],
  ["BRE1", "BRE2"],
  ["BRE3", "BRE4"],
  ["BRE5", "BRE6"],
  ["BUC1", "BUC2"],
  ["BUC3", "BUC4"],
  ["CHE1", "CHE2"],
  ["CHE3", "CHE4"],
  ["CHI1", "CHI2"],
  ["CHI3", "CHI4"],
  ["COL1", "COL2"],
  ["EPP1", "EPP2"],
  ["EPP3", "EPP4"],
  ["FIV1", "FIV2"],
  ["FIV3", "FIV4"],
  ["FRE1", "FRE2"],
  ["FRE3", "FRE4"],
  ["GOR1", "GOR2"],
  ["GPR1", "GPR2"],
  ["GPR3", "GPR4"],
  ["HAD1", "HAD2"],
  ["HAD3", "HAD4"],
  ["HAR1", "HAR2"],
  ["HAR3", "HAR4"],
  ["HAT1", "HAT2"],
  ["HAT3", "HAT4"],
  ["HAW1", "HAW2"],
  ["HAW3", "HAW4"],
  ["HOH1", "HOH2"],
  ["HOH3", "HOH4"],
  ["HOR1", "HOR2"],
  ["HOR3", "HOR4"],
  ["HUT1", "HUT2"],
  ["HUT3", "HUT4"],
  ["ILF1", "ILF2"],
  ["ILF3", "ILF4"],
  ["LOS1", "LOS2"],
  ["LOS3", "LOS4"],
  ["LOU1", "LOU2"],
  ["LOU3", "LOU4"],
  ["NEW1", "NEW2"],
  ["NEW3", "NEW4"],
  ["OLB1", "OLB2"],
  ["OLB3", "OLB4"],
  ["OPA1", "OPA2"],
  ["OPA3", "OPA4"],
  ["ORS1", "ORS2"],
  ["ORS3", "ORS4"],
  ["OSS1", "OSS2"],
  ["OSS3", "OSS4"],
  ["RED1", "RED2"],
  ["RED3", "RED4"],
  ["SHE1", "SHE2"],
  ["SHE3", "SHE4"],
  ["SLH1", "SLH2"],
  ["SLH3", "SLH4"],
  ["SOS1", "SOS2"],
  ["SOS3", "SOS4"],
  ["SWD1", "SWD2"],
  ["SWD3", "SWD4"],
  ["WAL1", "WAL2"],
  ["WAL3", "WAL4"],
  ["UPM1", "UPM2"],
  ["UPM3", "UPM4"],
  ["WAN1", "WAN2"],
  ["WAN3", "WAN4"],
  ["WAN5", "WAN6"],
  ["WES1", "WES2"],
  ["WES3", "WES4"],
  ["WFG1", "WFG2"],
  ["WFG3", "WFG4"],
  ["WIC1", "WIC2"],
  ["WIC3", "WIC4"],
  ["WOS1", "WOS2"],
  ["WOS3", "WOS4"],
  ["WWE1", "WWE2"],
  ["WWE3", "WWE4"],
];
