import {
  ConflictsArray,
} from "../utils";

export const divConfig = [{
  name: "1st XI Premier",
  teams: [
    "BRE1",
    "WAN1",
    "CHE1",
    "HAD1",
    "HOR1",
    "BIL1",
    "CHI1",
    "BEL1",
    "COL1",
    "HAW1",
  ],
}, {
  name: "1st XI Div 1",
  teams: [
    "BUC1",
    "ILF1",
    "SHE1",
    "WWE1",
    "FIV1",
    "HUT1",
    "LOU1",
    "UPM1",
    "OSS1",
    "HOH1",
  ],
}, {
  name: "1st XI Div 2",
  teams: [
    "GPR1",
    "SOS1",
    "OPA1",
    "ORS1",
    "HAT1",
    "BEN1",
    "WIC1",
    "FRE1",
    "LOS1",
    "WOS1",
  ],
}, {
  name: "1st XI Div 3",
  teams: [
    "OLB1",
    "SWD1",
    "HAR1",
    "WAL1",
    "ARD1",
    "EPP1",
    "GOR1",
    "SLH1",
    "WFG1",
    "WES1",
    // "RAI1",
    // "BAR1",
    // "NEW1",
    // "SPR1",
  ],
}, {
  name: "2nd XI Premier",
  teams: [
    "HOR2",
    "CHE2",
    "BRE2",
    "WAN2",
    "ILF2",
    "SHE2",
    "WWE2",
    "OPA2",
    "CHI2",
    "BUC2",
  ],
}, {
  name: "2nd XI Div 1",
  teams: [
    "UPM2",
    "WIC2",
    "HAW2",
    "LOU2",
    "HUT2",
    "COL2",
    "BIL2",
    "FRE2",
    "SWF2",
    "GPR2",
  ],
}, {
  name: "2nd XI Div 2",
  teams: [
    "BEL2",
    "SOS2",
    "HAR2",
    "WOS2",
    "OLB2",
    "OSS2",
    "ARD2",
    "HAD2",
    "LOS2",
    "EPP2",
  ],
}, {
  name: "2nd XI Div 3",
  teams: [
    "WES2",
    "ORS2",
    "BEN2",
    "FIV2",
    "SLH2",
    "WFG2",
    "GOR2",
    "WAL2",
    "HOH2",
    "HAT2",
  ],
}, {
  name: "3rd XI Premier",
  teams: [
    "UPM3",
    "BRE3",
    "SHE3",
    "HOR3",
    "HAW3",
    "HAR3",
    "WWE3",
    "WAN3",
    "ORS3",
    "HUT3",
  ],
}, {
  name: "3rd XI Div 1",
  teams: [
    "LOU3",
    "CHE3",
    "UPM4",
    "FRE3",
    "BIL3",
    "WAN4",
    "BUH3",
    "CHE4",
    "ILF3",
    "OPA3",
  ],
}, {
  name: "3rd XI Div 2",
  teams: [
    "BEL3",
    "OSS3",
    "WIC3",
    "CHI3",
    "FIV3",
    "LOU4",
    "SWF3",
    "HOR4",
    "BRE4",
    "HAR4",
  ],
}, {
  name: "3rd XI Div 3",
  teams: [
    "WAN5",
    "SOS3",
    "HAW4",
    "WAL3",
    "FRE4",
    "SLH3",
    "GPR3",
    "WFG3",
    "WOS3",
    "WES3",
  ],
}, {
  name: "4th XI Prem East",
  teams: [
    "HAT3",
    "ORS4",
    "LOS3",
    "HUT4",
    "BEL4",
    "BEN3",
    "BIL4",
    "ARD3",
    "CHE5",
    "BYE1",
  ],
}, {
  name: "4th XI Prem West",
  teams: [
    "HOH3",
    "OAP4",
    "BUH4",
    "UPM5",
    "BRE5",
    "LOU5",
    "SHE4",
    "EPP3",
    "WAL4",
    "BYE2",
  ],
}, {
  name: "4th XI Div 1 East",
  teams: [
    "ORS5",
    "SOS4",
    "HOH4",
    "SLH4",
    "LOS4",
    "BEL5",
    "BEN4",
    "HAT4",
    "OSS4",
    "BRE6",
    "OSS5",
    "WIC5",
  ],
}, {
  name: "4th XI Div 1 West",
  teams: [
    "GPR4",
    "SWF4",
    "GOR3",
    "HOR5",
    "OAP5",
    "ILF4",
    "WAN6",
    "CHI4",
    "HAW5",
    "ARD4",
    "HUT5",
    "FIV4",
  ],
}];

export const venConflicts: ConflictsArray = [
  ["ARD1", "ARD2"],
  ["ARD3", "ARD4"],
  ["BEL1", "BEL2"],
  ["BEL3", "BEL4"],
  ["BEN1", "BEN2"],
  ["BEN3", "BEN4"],
  ["BIL1", "BIL2"],
  ["BIL3", "BIL4"],
  ["BRE1", "BRE2"],
  ["BRE3", "BRE4"],
  ["BRE5", "BRE6"],
  ["BUC1", "BUC2"],
  ["BUC3", "BUC4"],
  ["CHE1", "CHE2"],
  ["CHE3", "CHE4"],
  ["CHE5", "CHE6"],
  ["CHI1", "CHI2"],
  ["CHI3", "CHI4"],
  ["COL1", "COL2"],
  ["EPP1", "EPP2"],
  ["EPP3", "EPP4"],
  ["FIV1", "FIV2"],
  ["FIV3", "FIV4"],
  ["FRE1", "FRE2"],
  ["FRE3", "FRE4"],
  ["GOR1", "GOR2"],
  ["GPR1", "GPR2"],
  ["GPR3", "GPR4"],
  ["HAD1", "HAD2"],
  ["HAD3", "HAD4"],
  ["HAR1", "HAR2"],
  ["HAR3", "HAR4"],
  ["HAT1", "HAT2"],
  ["HAT3", "HAT4"],
  ["HAW1", "HAW2"],
  ["HAW3", "HAW4"],
  ["HOH1", "HOH2"],
  ["HOH3", "HOH4"],
  ["HOR1", "HOR2"],
  ["HOR3", "HOR4"],
  ["HUT1", "HUT2"],
  ["HUT3", "HUT4"],
  ["ILF1", "ILF2"],
  ["ILF3", "ILF4"],
  ["LOS1", "LOS2"],
  ["LOS3", "LOS4"],
  ["LOU1", "LOU2"],
  ["LOU3", "LOU4"],
  ["OLB1", "OLB2"],
  ["OLB3", "OLB4"],
  ["OPA1", "OPA2"],
  ["OPA3", "OPA4"],
  ["ORS1", "ORS2"],
  ["ORS3", "ORS4"],
  ["OSS1", "OSS2"],
  ["OSS3", "OSS4"],
  ["SHE1", "SHE2"],
  ["SHE3", "SHE4"],
  ["SLH1", "SLH2"],
  ["SLH3", "SLH4"],
  ["SOS1", "SOS2"],
  ["SOS3", "SOS4"],
  ["SWD1", "SWD2"],
  ["SWD3", "SWD4"],
  ["WAL1", "WAL2"],
  ["WAL3", "WAL4"],
  ["UPM1", "UPM2"],
  ["UPM3", "UPM4"],
  ["WAN1", "WAN2"],
  ["WAN3", "WAN4"],
  ["WAN5", "WAN6"],
  ["WES1", "WES2"],
  ["WES3", "WES4"],
  ["WFG1", "WFG2"],
  ["WFG3", "WFG4"],
  ["WIC1", "WIC2"],
  ["WIC3", "WIC4"],
  ["WOS1", "WOS2"],
  ["WOS3", "WOS4"],
  ["WWE1", "WWE2"],
  ["WWE3", "WWE4"],
];
